#!/usr/bin/env bash
#Script that prints "Best school" * 10, and prints
#+ Hi, Best School on the ninth time.

i=1

while ((i < 9))
do
	if (( i == 4))
	then
		echo "bad luck"
	fi

	if ((i == 7))
	then
		echo "good luck"
	fi
	
	echo "Best School"
	(( i++ ))
done
